//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int id_Accounting { get; set; }
        public int id_Profer { get; set; }
        public int id_Student { get; set; }
        public int id_Book { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public Nullable<System.DateTime> DateOfAdoption { get; set; }
        public string NumberOfBooks { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Profer Profer { get; set; }
        public virtual Student Student { get; set; }
    }
}
