//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avtorization
    {
        public int id_Avtorization { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int id_Pofer { get; set; }
    
        public virtual Profer Profer { get; set; }
    }
}
