//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessLibraryEntities : DbContext
    {
        /// <summary>
        ///  Создание экземпляра класса Библиотеки Enitiy Fraemwork для БД Библиотеки
        /// </summary>
        /// 

        private static BusinessLibraryEntities _contex;

        public BusinessLibraryEntities()
            : base("name=BusinessLibraryEntities")
        {
        }

        /// <summary>
        /// Если модель не существует то пересоздаём, собственно модель
        /// В конце возращаем переменную с данными о самой БД
        /// </summary>
        /// <returns></returns>
        /// 

        public static BusinessLibraryEntities GetContex()
        {
            if (_contex == null)
            {
                _contex = new BusinessLibraryEntities();
            }

            return _contex;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounting> Accounting { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Avtor> Avtor { get; set; }
        public virtual DbSet<Avtorization> Avtorizations { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Profer> Profer { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
